#!/usr/bin/env python3
"""Publish everything under apps/ (plus generated apps like the flight
tracker) to docs/aiapps/<slug>/ and render a docs/index.html landing page
linking to each of them.

To add a new static app: drop a self-contained .html file in apps/ and
add an entry to STATIC_APPS below.
"""
from __future__ import annotations

import shutil
from pathlib import Path

APPS_SRC_DIR = Path("apps")
DOCS_DIR = Path("docs")
AIAPPS_DIR = DOCS_DIR / "aiapps"
LANDING_PATH = DOCS_DIR / "index.html"

# Apps whose HTML is authored directly (copied as-is into docs/aiapps/<slug>/index.html).
STATIC_APPS = [
    {
        "slug": "tmux-cheatsheet",
        "title": "tmux Cheat Sheet",
        "description": "Quick-reference tmux commands and key bindings.",
        "source": APPS_SRC_DIR / "tmux-cheatsheet.html",
    },
]

# Apps whose HTML is generated by another script (already written to
# docs/aiapps/<slug>/index.html by the time this script runs). Listed here
# only so the landing page can link to them.
GENERATED_APPS = [
    {
        "slug": "flight-price-tracker",
        "title": "DFW ↔ ORD Weekend Flight Prices",
        "description": "Daily-checked round-trip economy price for the next upcoming Friday→Sunday weekend.",
    },
]


def publish_static_apps() -> None:
    for app in STATIC_APPS:
        dest_dir = AIAPPS_DIR / app["slug"]
        dest_dir.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(app["source"], dest_dir / "index.html")


def build_landing_page() -> None:
    all_apps = GENERATED_APPS + STATIC_APPS
    cards = "\n".join(
        f'<li><a href="aiapps/{app["slug"]}/"><strong>{app["title"]}</strong></a>'
        f'<p>{app["description"]}</p></li>'
        for app in all_apps
    )

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>aiapps</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; max-width: 700px; margin: 3rem auto; padding: 0 1rem; color: #1a1a1a; }}
  h1 {{ font-size: 1.6rem; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ padding: 1rem 0; border-bottom: 1px solid #e0e0e0; }}
  a {{ font-size: 1.1rem; text-decoration: none; color: #2563eb; }}
  a:hover {{ text-decoration: underline; }}
  p {{ margin: 0.3rem 0 0; color: #666; font-size: 0.9rem; }}
</style>
</head>
<body>
<h1>aiapps</h1>
<ul>
{cards}
</ul>
</body>
</html>
"""
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    LANDING_PATH.write_text(html)


def main() -> None:
    publish_static_apps()
    build_landing_page()


if __name__ == "__main__":
    main()
